/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-12-29 17:32:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.Cliente;
import java.util.List;

public final class clienteList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"Error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\r\n");
      out.write("<title>List Clientes</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Nombre</th>\r\n");
      out.write("\t\t\t<th>Apellido</th>\r\n");
      out.write("\t\t\t<th>Tipo Doc</th>\r\n");
      out.write("\t\t\t<th>Num Doc</th>\r\n");
      out.write("\t\t\t<th>Tel Fijo</th>\r\n");
      out.write("\t\t\t<th>Tel Cel</th>\r\n");
      out.write("\t\t\t<th>Direccion</th>\r\n");
      out.write("\t\t\t<th>Ciudad</th>\r\n");
      out.write("\t\t\t<th>Provincia</th>\r\n");
      out.write("\t\t\t<th>Nacionalidad</th>\r\n");
      out.write("\t\t\t<th>E-mail</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			@SuppressWarnings("unchecked")
			List<Cliente> clientes = (List<Cliente>) session.getAttribute("clientes");
			int pos = 0;
			for (Cliente client : clientes) {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getNombre());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getApellido());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getTipoDoc());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getNumDoc());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getTelFijo());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getTelCel());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getDireccion());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getCiudad());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getProvincia());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getNacionalidad());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(client.getE_mail());
      out.write("</td>\r\n");
      out.write("\t\t\t<td><a href=\"ClienteDeleteServlet?clienteId=");
      out.print(client.getClienteId());
      out.write("\">Eliminar</a></td>\r\n");
      out.write("\t\t\t<td><a href=\"clienteUpdate.jsp?pos=");
      out.print(pos);
      out.write("\">Modificar</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

				pos++;
			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("<button id=\"CancelClient\">volver</button>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"http://code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
